# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Tom\Desktop\AI4TSF\login\LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(643, 351)
        self.frame = QtWidgets.QFrame(LoginWindow)
        self.frame.setGeometry(QtCore.QRect(10, 0, 631, 341))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frameBg = QtWidgets.QFrame(self.frame)
        self.frameBg.setGeometry(QtCore.QRect(10, 50, 271, 282))
        self.frameBg.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.frameBg.setStyleSheet("#frameBg {\n"
"    \n"
"    color: rgb(100, 100, 100);\n"
"    background-color: rgb(245, 245, 245);\n"
"\n"
"    border: 1px solid #c7cacd;\n"
"        border-radius: 4px;\n"
"}")
        self.frameBg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBg.setObjectName("frameBg")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameBg)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frameBg)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/3/res/界面.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.frameLoginRegister = QtWidgets.QFrame(self.frame)
        self.frameLoginRegister.setGeometry(QtCore.QRect(310, 50, 311, 282))
        self.frameLoginRegister.setStyleSheet("#frameLoginRegister {\n"
"    \n"
"    color: rgb(100, 100, 100);\n"
"    background-color: rgb(245, 245, 245);\n"
"\n"
"    border: 1px solid #c7cacd;\n"
"        border-radius: 4px;\n"
"}")
        self.frameLoginRegister.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLoginRegister.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLoginRegister.setObjectName("frameLoginRegister")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frameLoginRegister)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButtonRegisterPage = QtWidgets.QPushButton(self.frameLoginRegister)
        self.pushButtonRegisterPage.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonRegisterPage.setStyleSheet("QPushButton {\n"
"        border: 1px solid #c7cacd;\n"
"        border-radius: 4px;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #c7cacd;\n"
"    }")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/3/res/编辑.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRegisterPage.setIcon(icon)
        self.pushButtonRegisterPage.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonRegisterPage.setObjectName("pushButtonRegisterPage")
        self.gridLayout_3.addWidget(self.pushButtonRegisterPage, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.frameLoginRegister)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 1, 1, 1)
        self.pushButtonLoginPage = QtWidgets.QPushButton(self.frameLoginRegister)
        self.pushButtonLoginPage.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonLoginPage.setStyleSheet("QPushButton {\n"
"        border: 1px solid #c7cacd;\n"
"        border-radius: 4px;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #c7cacd;\n"
"    }")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/3/res/填选购人.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLoginPage.setIcon(icon1)
        self.pushButtonLoginPage.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonLoginPage.setObjectName("pushButtonLoginPage")
        self.gridLayout_3.addWidget(self.pushButtonLoginPage, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frameLoginRegister)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButtonForget = QtWidgets.QPushButton(self.page)
        self.pushButtonForget.setMinimumSize(QtCore.QSize(70, 23))
        self.pushButtonForget.setStyleSheet("QPushButton {\n"
"        border: 1px solid #c7cacd;\n"
"        border-radius: 4px;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #c7cacd;\n"
"    }")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/3/res/提示.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonForget.setIcon(icon2)
        self.pushButtonForget.setObjectName("pushButtonForget")
        self.gridLayout_4.addWidget(self.pushButtonForget, 2, 2, 1, 1)
        self.pushButtonLogin = QtWidgets.QPushButton(self.page)
        self.pushButtonLogin.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonLogin.setStyleSheet("QPushButton {\n"
"        border: 1px solid #c7cacd;\n"
"        border-radius: 4px;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #c7cacd;\n"
"    }")
        self.pushButtonLogin.setIcon(icon1)
        self.pushButtonLogin.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.gridLayout_4.addWidget(self.pushButtonLogin, 3, 0, 1, 3)
        self.lineEditUsername = QtWidgets.QLineEdit(self.page)
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.gridLayout_4.addWidget(self.lineEditUsername, 0, 1, 1, 2)
        self.lineEditPassword = QtWidgets.QLineEdit(self.page)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.gridLayout_4.addWidget(self.lineEditPassword, 1, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.page)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.page)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_4.addWidget(self.checkBox, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEditRegisterName = QtWidgets.QLineEdit(self.page_2)
        self.lineEditRegisterName.setObjectName("lineEditRegisterName")
        self.gridLayout_5.addWidget(self.lineEditRegisterName, 0, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEditEmail = QtWidgets.QLineEdit(self.page_2)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.gridLayout_5.addWidget(self.lineEditEmail, 1, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 2, 0, 1, 1)
        self.lineEditRegisterPassword1 = QtWidgets.QLineEdit(self.page_2)
        self.lineEditRegisterPassword1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditRegisterPassword1.setObjectName("lineEditRegisterPassword1")
        self.gridLayout_5.addWidget(self.lineEditRegisterPassword1, 2, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 3, 0, 1, 1)
        self.lineEditRegisterPassword2 = QtWidgets.QLineEdit(self.page_2)
        self.lineEditRegisterPassword2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditRegisterPassword2.setObjectName("lineEditRegisterPassword2")
        self.gridLayout_5.addWidget(self.lineEditRegisterPassword2, 3, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 4, 0, 1, 1)
        self.lineEditVerify = QtWidgets.QLineEdit(self.page_2)
        self.lineEditVerify.setObjectName("lineEditVerify")
        self.gridLayout_5.addWidget(self.lineEditVerify, 4, 1, 1, 1)
        self.pushButtonSend = QtWidgets.QPushButton(self.page_2)
        self.pushButtonSend.setMinimumSize(QtCore.QSize(65, 23))
        self.pushButtonSend.setStyleSheet("QPushButton {\n"
"        border: 1px solid #c7cacd;\n"
"        border-radius: 4px;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #c7cacd;\n"
"    }")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/3/res/confirm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSend.setIcon(icon3)
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.gridLayout_5.addWidget(self.pushButtonSend, 4, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 5, 0, 1, 3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_5.addWidget(self.checkBox_2, 6, 0, 1, 3)
        self.pushButtonRegister = QtWidgets.QPushButton(self.page_2)
        self.pushButtonRegister.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonRegister.setStyleSheet("QPushButton {\n"
"        border: 1px solid #c7cacd;\n"
"        border-radius: 4px;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #c7cacd;\n"
"    }")
        self.pushButtonRegister.setIcon(icon)
        self.pushButtonRegister.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonRegister.setObjectName("pushButtonRegister")
        self.gridLayout_5.addWidget(self.pushButtonRegister, 7, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_10 = QtWidgets.QLabel(self.page_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.lineEditEmail2 = QtWidgets.QLineEdit(self.page_3)
        self.lineEditEmail2.setObjectName("lineEditEmail2")
        self.gridLayout_6.addWidget(self.lineEditEmail2, 0, 1, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.page_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 1, 0, 1, 1)
        self.lineEditNewPassword = QtWidgets.QLineEdit(self.page_3)
        self.lineEditNewPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditNewPassword.setObjectName("lineEditNewPassword")
        self.gridLayout_6.addWidget(self.lineEditNewPassword, 1, 1, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.page_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 2, 0, 1, 1)
        self.lineEditNewPassword2 = QtWidgets.QLineEdit(self.page_3)
        self.lineEditNewPassword2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditNewPassword2.setObjectName("lineEditNewPassword2")
        self.gridLayout_6.addWidget(self.lineEditNewPassword2, 2, 1, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.page_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 3, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_6.addWidget(self.lineEdit_9, 3, 1, 1, 1)
        self.pushButtonVerify2 = QtWidgets.QPushButton(self.page_3)
        self.pushButtonVerify2.setMinimumSize(QtCore.QSize(65, 23))
        self.pushButtonVerify2.setStyleSheet("QPushButton {\n"
"        border: 1px solid #c7cacd;\n"
"        border-radius: 4px;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #c7cacd;\n"
"    }")
        self.pushButtonVerify2.setIcon(icon3)
        self.pushButtonVerify2.setObjectName("pushButtonVerify2")
        self.gridLayout_6.addWidget(self.pushButtonVerify2, 3, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 4, 0, 1, 3)
        self.checkBox_3 = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_6.addWidget(self.checkBox_3, 5, 0, 1, 3)
        self.pushButtonForgetOk = QtWidgets.QPushButton(self.page_3)
        self.pushButtonForgetOk.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonForgetOk.setStyleSheet("QPushButton {\n"
"        border: 1px solid #c7cacd;\n"
"        border-radius: 4px;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border: 1px solid #c7cacd;\n"
"    }")
        self.pushButtonForgetOk.setIcon(icon3)
        self.pushButtonForgetOk.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonForgetOk.setObjectName("pushButtonForgetOk")
        self.gridLayout_6.addWidget(self.pushButtonForgetOk, 6, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout_3.addWidget(self.stackedWidget, 1, 0, 1, 3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 631, 41))
        self.frame_2.setStyleSheet("#frame_2{\n"
"background-color:rgb(76, 114, 176)\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
"    background-color:rgba(0,0,0,0);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(70, 41))
        self.pushButton_3.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"font: 9pt \"黑体\";")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/3/res/数据质控.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon4)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        spacerItem1 = QtWidgets.QSpacerItem(438, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setEnabled(True)
        self.pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton.setStyleSheet("border-image: url(:/3/res/minus.png)")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_2.setStyleSheet("border-image: url(:/3/res/closev.png)")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)

        self.retranslateUi(LoginWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Form"))
        self.pushButtonRegisterPage.setText(_translate("LoginWindow", "注册"))
        self.pushButtonLoginPage.setText(_translate("LoginWindow", "登录"))
        self.label_2.setText(_translate("LoginWindow", "用户密码："))
        self.pushButtonForget.setText(_translate("LoginWindow", "忘记密码"))
        self.pushButtonLogin.setText(_translate("LoginWindow", "登录"))
        self.lineEditUsername.setPlaceholderText(_translate("LoginWindow", "邮箱地址/账号"))
        self.lineEditPassword.setPlaceholderText(_translate("LoginWindow", "密码"))
        self.label.setText(_translate("LoginWindow", "账    号："))
        self.checkBox.setText(_translate("LoginWindow", "记住"))
        self.label_4.setText(_translate("LoginWindow", "账    号："))
        self.lineEditRegisterName.setPlaceholderText(_translate("LoginWindow", "用户账号"))
        self.label_5.setText(_translate("LoginWindow", "邮    箱："))
        self.lineEditEmail.setPlaceholderText(_translate("LoginWindow", "邮箱地址"))
        self.label_6.setText(_translate("LoginWindow", "用户密码："))
        self.lineEditRegisterPassword1.setPlaceholderText(_translate("LoginWindow", "密码"))
        self.label_7.setText(_translate("LoginWindow", "确认密码："))
        self.lineEditRegisterPassword2.setPlaceholderText(_translate("LoginWindow", "确认密码"))
        self.label_8.setText(_translate("LoginWindow", "验 证 码："))
        self.lineEditVerify.setPlaceholderText(_translate("LoginWindow", "邮箱验证码"))
        self.pushButtonSend.setText(_translate("LoginWindow", "发送"))
        self.checkBox_2.setText(_translate("LoginWindow", "注册后直接登录"))
        self.pushButtonRegister.setText(_translate("LoginWindow", "注册"))
        self.label_10.setText(_translate("LoginWindow", "账    号："))
        self.lineEditEmail2.setPlaceholderText(_translate("LoginWindow", "用户账号"))
        self.label_11.setText(_translate("LoginWindow", "新 密 码："))
        self.lineEditNewPassword.setPlaceholderText(_translate("LoginWindow", "密码"))
        self.label_12.setText(_translate("LoginWindow", "确认密码："))
        self.lineEditNewPassword2.setPlaceholderText(_translate("LoginWindow", "确认密码"))
        self.label_13.setText(_translate("LoginWindow", "验 证 码："))
        self.lineEdit_9.setPlaceholderText(_translate("LoginWindow", "邮箱验证码"))
        self.pushButtonVerify2.setText(_translate("LoginWindow", "发送"))
        self.checkBox_3.setText(_translate("LoginWindow", "找回密码后直接登录"))
        self.pushButtonForgetOk.setText(_translate("LoginWindow", "确认"))
        self.pushButton_3.setText(_translate("LoginWindow", "AI4TSF"))
import one_rc
